

GET http://localhost:8081/book?title=1984

###

GET http://localhost:8081/book/all

###

POST http://localhost:8081/book
Content-Type: application/json

{
  "title": "King in Yellow",
  "author": "Robert W. Chambers",
  "description": "A collection of weird and supernatural stories"
}


